include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - linux/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    prefer_relative_imports: true
    prefer_initializing_formals: false
